package it.gov.pagopa.pu.debtpositions.util;

public class ErrorCodeConstants {
  private ErrorCodeConstants() {}

  public static final String ERROR_CODE_IMMUTABLE_FIELD = "IMMUTABLE_FIELD";
  public static final String ERROR_CODE_INVALID_INSTALLMENT = "INVALID_INSTALLMENT";
  public static final String ERROR_CODE_TRANSFER_NOT_FOUND = "TRANSFER_NOT_FOUND";
  public static final String ERROR_CODE_INVALID_DATE_TIME_INTERVAL = "INVALID_DATE_FILTER_INTERVAL";
  public static final String ERROR_CODE_INSTALLMENT_MAPPING_ERROR = "INSTALLMENT_MAPPING_ERROR";
  public static final String ERROR_CODE_DEBT_POSITION_TYPE_ORG_NOT_FOUND = "DEBT_POSITION_TYPE_ORG_NOT_FOUND";
  public static final String ERROR_CODE_RECEIPT_NOT_FOUND = "RECEIPT_NOT_FOUND";
  public static final String ERROR_CODE_INSTALLMENT_NOT_FOUND = "INSTALLMENT_NOT_FOUND";
  public static final String ERROR_CODE_TOO_MANY_EXPORTED_RECORDS = "TOO_MANY_EXPORTED_RECORDS";
  public static final String ERROR_CODE_ORGANIZATION_NOT_FOUND = "ORGANIZATION_NOT_FOUND";
  public static final String ERROR_CODE_INSTALLMENT_ALREADY_EXISTS = "INSTALLMENT_ALREADY_EXISTS";
  public static final String ERROR_CODE_TOO_MANY_PAYMENT_OPTIONS = "TOO_MANY_PAYMENT_OPTIONS";
  public static final String ERROR_CODE_TOO_MANY_INSTALLMENTS = "TOO_MANY_INSTALLMENTS";
  public static final String ERROR_CODE_DEBT_POSITION_NOT_FOUND = "DEBT_POSITION_NOT_FOUND";
  public static final String ERROR_CODE_INVALID_INSTALLMENT_NAV_MISMATCH = "INVALID_INSTALLMENT_NAV_MISMATCH";
  public static final String ERROR_CODE_INVALID_RECEIPT_ORG_MISMATCH = "INVALID_RECEIPT_ORG_MISMATCH";
  public static final String ERROR_CODE_INVALID_RECEIPT_ORG = "INVALID_RECEIPT_ORG";
  public static final String ERROR_CODE_INVALID_PAYMENT_INDEX = "INVALID_PAYMENT_INDEX";
  public static final String ERROR_CODE_INVALID_IUV = "INVALID_IUV";
  public static final String ERROR_CODE_DEBT_POSITION_ALREADY_EXISTS = "DEBT_POSITION_ALREADY_EXISTS";
  public static final String ERROR_CODE_MISSING_DEBT_POSITION_TYPE_ORG = "MISSING_DEBT_POSITION_TYPE_ORG";
  public static final String ERROR_CODE_MISSING_PAYMENT_OPTION = "MISSING_PAYMENT_OPTION";
  public static final String ERROR_CODE_DUPLICATED_PAYMENT_OPTION_INDEX = "DUPLICATED_PAYMENT_OPTION_INDEX";
  public static final String ERROR_CODE_MISSING_INSTALLMENT = "MISSING_INSTALLMENT";
  public static final String ERROR_CODE_DIFFERENT_DEBTORS_IN_SAME_PO = "DIFFERENT_DEBTORS_IN_SAME_PO";
  public static final String ERROR_CODE_MULTIDEBTOR_DISABLED = "MULTIDEBTOR_DISABLED";
  public static final String ERROR_CODE_INVALID_DEBT_POSITION_STATUS = "INVALID_DEBT_POSITION_STATUS";
  public static final String ERROR_CODE_MISSING_REMITTANCE_INFORMATION = "MISSING_REMITTANCE_INFORMATION";
  public static final String ERROR_CODE_INVALID_CENTS_AMOUNT = "INVALID_CENTS_AMOUNT";
  public static final String ERROR_CODE_INVALID_AMOUNT = "INVALID_AMOUNT";
  public static final String ERROR_CODE_INVALID_BALANCE = "INVALID_BALANCE";
  public static final String ERROR_CODE_INVALID_LEGACY_PAYMENT_METADATA = "INVALID_LEGACY_PAYMENT_METADATA";
  public static final String ERROR_CODE_INVALID_INSTALLMENT_AMOUNT_CENTS = "INVALID_INSTALLMENT_AMOUNT_CENTS";
  public static final String ERROR_CODE_MISSING_IUV = "MISSING_IUV";
  public static final String ERROR_CODE_MISSING_DUE_DATE = "MISSING_DUE_DATE";
  public static final String ERROR_CODE_INVALID_DUE_DATE = "INVALID_DUE_DATE";
  public static final String ERROR_CODE_MISSING_DEBTOR = "MISSING_DEBTOR";
  public static final String ERROR_CODE_INVALID_VAT_CODE = "INVALID_VAT_CODE";
  public static final String ERROR_CODE_INVALID_FULLNAME = "INVALID_FULLNAME";
  public static final String ERROR_CODE_INVALID_EMAIL = "INVALID_EMAIL";
  public static final String ERROR_CODE_MISSING_TRANSFER = "MISSING_TRANSFER";
  public static final String ERROR_CODE_TOO_MANY_TRANSFERS_FOR_INSTALLMENT = "TOO_MANY_TRANSFERS_FOR_INSTALLMENT";
  public static final String ERROR_CODE_DUPLICATED_TRANSFER_INDEX = "DUPLICATED_TRANSFER_INDEX";
  public static final String ERROR_CODE_INVALID_TRANSFER_INDEX = "INVALID_TRANSFER_INDEX";
  public static final String ERROR_CODE_INVALID_FIELDS = "INVALID_FIELDS";
  public static final String ERROR_CODE_INVALID_IBAN = "INVALID_IBAN";
  public static final String ERROR_CODE_INVALID_POSTAL_IBAN = "INVALID_POSTAL_IBAN";
  public static final String ERROR_CODE_MISSING_TAXONOMY_CATEGORY = "MISSING_TAXONOMY_CATEGORY";
  public static final String ERROR_CODE_INVALID_TAXONOMY_CATEGORY = "INVALID_TAXONOMY_CATEGORY";
}
