openapi: 3.0.1
info:
  title: p4pa-debt-positions
  description: Api and Models
  version: 0.0.1
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  /debt-positions:
    post:
      tags:
        - debt-position
      operationId: createDebtPosition
      parameters:
        - name: massive
          in: query
          description: Indicates if the operation is massive (true) or single (false).
          required: false
          schema:
            type: boolean
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DebtPositionDTO"
        required: true
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DebtPositionDTO"
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DebtPositionErrorDTO"
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DebtPositionErrorDTO"
        "409":
          description: Conflict
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DebtPositionErrorDTO"
        "500":
          description: Internal server error
  /installments/{organizationId}/{nav}:
    get:
      tags:
        - installment
      operationId: getInstallmentsByOrganizationIdAndNav
      parameters:
        - name: organizationId
          in: path
          required: true
          schema:
            type: integer
            format: int64
          description: The ID of the organization
        - name: nav
          in: path
          required: true
          schema:
            type: string
          description: The nav of the installments
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/InstallmentDTO"
        "400":
          description: Invalid request
        "500":
          description: Internal server error
  /receipts:
    post:
      tags:
        - receipt
      operationId: createReceipt
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ReceiptWithAdditionalNodeDataDTO"
        required: true
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ReceiptDTO"
        "400":
          description: Invalid request
        "409":
          description: Debt position already exists
        "500":
          description: Internal server error
  /debt-positions/{debtPositionId}/finalize-sync-status:
    put:
      tags:
        - debt-position
      operationId: finalizeSyncStatus
      parameters:
        - name: debtPositionId
          in: path
          required: true
          schema:
            type: integer
            format: int64
          description: The ID of the debt position
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SyncStatusUpdateRequestDTO"
        required: true
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DebtPositionDTO'
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DebtPositionErrorDTO'
        "404":
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DebtPositionErrorDTO'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DebtPositionErrorDTO'
  /debt-positions/{debtPositionId}/check-installment-expiration:
    put:
      tags:
        - debt-position
      operationId: checkAndUpdateInstallmentExpiration
      parameters:
        - name: debtPositionId
          in: path
          required: true
          schema:
            type: integer
            format: int64
          description: The ID of the debt position
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DebtPositionDTO'
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DebtPositionErrorDTO'
        "404":
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DebtPositionErrorDTO'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DebtPositionErrorDTO'
  /transfers/{transferId}/reported:
    put:
      tags:
        - transfer
      operationId: notifyReportedTransferId
      parameters:
        - name: transferId
          in: path
          required: true
          schema:
            type: integer
            format: int64
          description: The ID of the transfer
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DebtPositionDTO'
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DebtPositionErrorDTO'
        "404":
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DebtPositionErrorDTO'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DebtPositionErrorDTO'
security:
  - BearerAuth: []
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
  schemas:
    DebtPositionDTO:
      required:
        - organizationId
        - debtPositionTypeOrgId
        - paymentOptions
        - flagPagoPaPayment
      type: object
      properties:
        debtPositionId:
          type: integer
          format: int64
        iupdOrg:
          type: string
        description:
          type: string
        status:
          $ref: "#/components/schemas/DebtPositionStatus"
        debtPositionOrigin:
          $ref: "#/components/schemas/DebtPositionOrigin"
        organizationId:
          type: integer
          format: int64
        debtPositionTypeOrgId:
          type: integer
          format: int64
        validityDate:
          type: string
          format: date-time
        flagIuvVolatile:
          type: boolean
        multiDebtor:
          type: boolean
        flagPagoPaPayment:
          type: boolean
        creationDate:
          type: string
          format: date-time
        updateDate:
          type: string
          format: date-time
        paymentOptions:
          type: array
          items:
            $ref: "#/components/schemas/PaymentOptionDTO"
    PaymentOptionDTO:
      required:
        - installments
        - totalAmountCents
        - paymentOptionType
      type: object
      properties:
        paymentOptionId:
          type: integer
          format: int64
        debtPositionId:
          type: integer
          format: int64
        totalAmountCents:
          type: integer
          format: int64
        status:
          $ref: "#/components/schemas/PaymentOptionStatus"
        dueDate:
          type: string
          format: date-time
        description:
          type: string
        paymentOptionType:
          type: string
          enum:
            - SINGLE_INSTALLMENT
            - INSTALLMENTS
            - DOWN_PAYMENT
        installments:
          type: array
          items:
            $ref: "#/components/schemas/InstallmentDTO"
    InstallmentDTO:
      required:
        - amountCents
        - debtor
        - remittanceInformation
        - transfers
      type: object
      properties:
        installmentId:
          type: integer
          format: int64
        paymentOptionId:
          type: integer
          format: int64
        status:
          $ref: "#/components/schemas/InstallmentStatus"
        syncStatus:
          $ref: "#/components/schemas/InstallmentSyncStatus"
        iupdPagopa:
          type: string
        iud:
          type: string
        iuv:
          type: string
        iur:
          type: string
        iuf:
          type: string
        nav:
          type: string
        dueDate:
          type: string
          format: date-time
        paymentTypeCode:
          type: string
        amountCents:
          type: integer
          format: int64
        remittanceInformation:
          type: string
        balance:
          type: string
        legacyPaymentMetadata:
          type: string
        debtor:
          $ref: "#/components/schemas/PersonDTO"
        transfers:
          type: array
          items:
            $ref: "#/components/schemas/TransferDTO"
        notificationDate:
          type: string
          format: date-time
        ingestionFlowFileId:
          type: integer
          format: int64
        ingestionFlowFileLineNumber:
          type: integer
          format: int64
        receiptId:
          type: integer
          format: int64
        creationDate:
          type: string
          format: date-time
        updateDate:
          type: string
          format: date-time
    TransferDTO:
      required:
        - amountCents
        - category
        - orgFiscalCode
        - orgName
        - remittanceInformation
      type: object
      properties:
        transferId:
          type: integer
          format: int64
        installmentId:
          type: integer
          format: int64
        orgFiscalCode:
          type: string
        orgName:
          type: string
        amountCents:
          type: integer
          format: int64
        remittanceInformation:
          type: string
        stampType:
          type: string
        stampHashDocument:
          type: string
        stampProvincialResidence:
          type: string
        iban:
          type: string
        postalIban:
          type: string
        category:
          type: string
        transferIndex:
          type: integer
          format: int32
    ReceiptDTO:
      type: object
      required:
        - receiptSource
        - paymentReceiptId
        - noticeNumber
        - orgFiscalCode
        - outcome
        - creditorReferenceId
        - paymentAmountCents
        - description
        - companyName
        - idPsp
        - pspCompanyName
        - idChannel
        - channelDescription
        - debtor
        - payer
      properties:
        receiptId:
          type: integer
          format: int64
        ingestionFlowFileId:
          type: integer
          format: int64
        receiptOrigin:
          type: string
        paymentReceiptId:
          type: string
        noticeNumber:
          type: string
        paymentNote:
          type: string
        orgFiscalCode:
          type: string
        outcome:
          type: string
        creditorReferenceId:
          type: string
        paymentAmountCents:
          type: integer
          format: int64
        description:
          type: string
        companyName:
          type: string
        officeName:
          type: string
        idPsp:
          type: string
        pspFiscalCode:
          type: string
        pspPartitaIva:
          type: string
        pspCompanyName:
          type: string
        idChannel:
          type: string
        channelDescription:
          type: string
        paymentMethod:
          type: string
        feeCents:
          type: integer
          format: int64
        paymentDateTime:
          type: string
          format: date-time
        applicationDate:
          type: string
          format: date-time
        transferDate:
          type: string
          format: date-time
        standin:
          type: boolean
        debtor:
          $ref: "#/components/schemas/PersonDTO"
        payer:
          $ref: "#/components/schemas/PersonDTO"
        creationDate:
          type: string
          format: date-time
        updateDate:
          type: string
          format: date-time
    ReceiptTransferDTO:
      required:
        - idTransfer
        - transferAmountCents
        - fiscalCodePA
        - remittanceInformation
        - transferCategory
      type: object
      properties:
        idTransfer:
          type: integer
          format: int32
        transferAmountCents:
          type: integer
          format: int64
        fiscalCodePA:
          type: string
        companyName:
          type: string
        mbdAttachment:
          type: string
          format: byte
        iban:
          type: string
        remittanceInformation:
          type: string
        transferCategory:
          type: string
        metadata:
          type: object
          additionalProperties:
            type: string
    ReceiptWithAdditionalNodeDataDTO:
      allOf:
        - $ref: "#/components/schemas/ReceiptDTO"
        - type: object
          required:
            - transfers
          properties:
            transfers:
              type: array
              minItems: 1
              items:
                $ref: "#/components/schemas/ReceiptTransferDTO"
            metadata:
              type: object
              additionalProperties:
                type: string
    PersonDTO:
      required:
        - email
        - fullName
        - entityType
        - fiscalCode
      type: object
      properties:
        entityType:
          type: string
          enum:
            - F
            - G
        fiscalCode:
          type: string
        fullName:
          type: string
        address:
          type: string
        civic:
          type: string
        postalCode:
          type: string
        location:
          type: string
        province:
          type: string
        nation:
          type: string
        email:
          type: string
    DebtPositionStatus:
      type: string
      enum:
        - TO_SYNC
        - REPORTED
        - PAID
        - PARTIALLY_PAID
        - CANCELLED
        - EXPIRED
        - UNPAID
        - DRAFT
    DebtPositionOrigin:
      type: string
      enum:
        - ORDINARY
        - ORDINARY_SIL
        - SPONTANEOUS
        - SECONDARY_ORG
        - RECEIPT_FILE
        - RECEIPT_PAGOPA
        - REPORTING_PAGOPA
    PaymentOptionStatus:
      type: string
      enum:
        - TO_SYNC
        - REPORTED
        - PAID
        - PARTIALLY_PAID
        - CANCELLED
        - INVALID
        - EXPIRED
        - UNPAID
        - DRAFT
    InstallmentStatus:
      type: string
      enum:
        - TO_SYNC
        - REPORTED
        - PAID
        - CANCELLED
        - INVALID
        - EXPIRED
        - UNPAID
        - DRAFT
    SyncStatusUpdateRequestDTO:
      type: object
      additionalProperties:
        $ref: "#/components/schemas/IupdSyncStatusUpdateDTO"
    IupdSyncStatusUpdateDTO:
      type: object
      properties:
        newStatus:
          $ref: "#/components/schemas/InstallmentStatus"
        iupdPagopa:
          type: string
    InstallmentSyncStatus:
      required:
        - syncStatusFrom
        - syncStatusTo
      type: object
      properties:
        syncStatusFrom:
          $ref: "#/components/schemas/InstallmentStatus"
        syncStatusTo:
          $ref: "#/components/schemas/InstallmentStatus"
    DebtPositionErrorDTO:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          enum:
            - DEBT_POSITION_BAD_REQUEST
            - DEBT_POSITION_CONFLICT
            - DEBT_POSITION_FORBIDDEN
            - DEBT_POSITION_GENERIC_ERROR
            - DEBT_POSITION_NOT_FOUND
        message:
          type: string
    DebtPositionTypeOrgDTO:
      required:
        - debtPositionTypeId
        - organizationId
        - code
        - description
        - iban
      type: object
      properties:
        debtPositionTypeOrgId:
          type: integer
          format: int64
        debtPositionTypeId:
          type: integer
          format: int64
        organizationId:
          type: integer
          format: int64
        balance:
          type: string
        code:
          type: string
        description:
          type: string
        iban:
          type: string
        postalIban:
          type: string
        postalAccountCode:
          type: string
        holderPostalCc:
          type: string
        orgSector:
          type: string
        xsdDefinitionRef:
          type: string
        amountCents:
          type: integer
          format: int64
        externalPaymentUrl:
          type: string
        flagAnonymousFiscalCode:
          type: boolean
        flagMandatoryDueDate:
          type: boolean
        flagSpontaneous:
          type: boolean
        flagNotifyIo:
          type: boolean
        ioTemplateMessage:
          type: string
        flagActive:
          type: boolean
        flagNotifyOutcomePush:
          type: boolean
        notifyOutcomePushOrgSilServiceId:
          type: integer
          format: int64
        flagAmountActualization:
          type: boolean
        amountActualizationOrgSilServiceId:
          type: integer
          format: int64
        flagExternal:
          type: boolean
