openapi: 3.0.1
info:
  title: p4pa-debt-positions
  description: Api and Models
  version: 0.0.1
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  /debt-positions:
    post:
      tags:
        - debt-position
      operationId: createDebtPosition
      parameters:
        - name: massive
          in: query
          description: Indicates if the operation is massive (true) or single (false).
          required: false
          schema:
            type: boolean
        - name: pagopaPayment
          in: query
          description: Indicates if IUV should be generated or not.
          required: false
          schema:
            type: boolean
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DebtPositionDTO"
        required: true
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DebtPositionDTO"
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DebtPositionErrorDTO"
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DebtPositionErrorDTO"
        "409":
          description: Conflict
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DebtPositionErrorDTO"
        "500":
          description: Internal server error
  /receipts:
    post:
      tags:
        - receipt
      operationId: createReceipt
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ReceiptDTO"
        required: true
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ReceiptDTO"
        "400":
          description: Invalid request
        "409":
          description: Debt position already exists
        "500":
          description: Internal server error
  /debt-positions/{debtPositionId}/finalize-sync-status:
    put:
      tags:
        - debt-position
      operationId: finalizeSyncStatus
      parameters:
        - name: debtPositionId
          in: path
          required: true
          schema:
            type: integer
            format: int64
          description: The ID of the debt position
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SyncStatusUpdateRequestDTO"
        required: true
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DebtPositionDTO'
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DebtPositionErrorDTO'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DebtPositionErrorDTO'
  /transfers/{transferId}/reported:
    put:
      tags:
        - transfer
      operationId: notifyReportedTransferId
      parameters:
        - name: transferId
          in: path
          required: true
          schema:
            type: integer
            format: int64
          description: The ID of the transfer
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DebtPositionDTO'
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DebtPositionErrorDTO'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DebtPositionErrorDTO'
security:
  - BearerAuth: []
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
  schemas:
    DebtPositionDTO:
      required:
        - organizationId
        - debtPositionTypeOrgId
        - paymentOptions
      type: object
      properties:
        debtPositionId:
          type: integer
          format: int64
        iupdOrg:
          type: string
        description:
          type: string
        status:
          $ref: "#/components/schemas/DebtPositionStatus"
        debtPositionOrigin:
          $ref: "#/components/schemas/DebtPositionOrigin"
        ingestionFlowFileId:
          type: integer
          format: int64
        ingestionFlowFileLineNumber:
          type: integer
          format: int64
        organizationId:
          type: integer
          format: int64
        debtPositionTypeOrgId:
          type: integer
          format: int64
        notificationDate:
          type: string
          format: date-time
        validityDate:
          type: string
          format: date-time
        flagIuvVolatile:
          type: boolean
        creationDate:
          type: string
          format: date-time
        updateDate:
          type: string
          format: date-time
        paymentOptions:
          type: array
          items:
            $ref: "#/components/schemas/PaymentOptionDTO"
    PaymentOptionDTO:
      required:
        - installments
        - totalAmountCents
        - paymentOptionType
      type: object
      properties:
        paymentOptionId:
          type: integer
          format: int64
        debtPositionId:
          type: integer
          format: int64
        totalAmountCents:
          type: integer
          format: int64
        status:
          $ref: "#/components/schemas/PaymentOptionStatus"
        multiDebtor:
          type: boolean
        dueDate:
          type: string
          format: date-time
        description:
          type: string
        paymentOptionType:
          type: string
          enum:
            - SINGLE_INSTALLMENT
            - INSTALMENTS
            - DOWN_PAYMENT
        installments:
          type: array
          items:
            $ref: "#/components/schemas/InstallmentDTO"
    InstallmentDTO:
      required:
        - amountCents
        - debtor
        - remittanceInformation
        - transfers
      type: object
      properties:
        installmentId:
          type: integer
          format: int64
        paymentOptionId:
          type: integer
          format: int64
        status:
          $ref: "#/components/schemas/InstallmentStatus"
        syncStatus:
          $ref: "#/components/schemas/InstallmentSyncStatus"
        iupdPagopa:
          type: string
        iud:
          type: string
        iuv:
          type: string
        iur:
          type: string
        iuf:
          type: string
        nav:
          type: string
        dueDate:
          type: string
          format: date-time
        paymentTypeCode:
          type: string
        amountCents:
          type: integer
          format: int64
        notificationFeeCents:
          type: integer
          format: int64
        remittanceInformation:
          type: string
        humanFriendlyRemittanceInformation:
          type: string
        balance:
          type: string
        legacyPaymentMetadata:
          type: string
        debtor:
          $ref: "#/components/schemas/PersonDTO"
        transfers:
          type: array
          items:
            $ref: "#/components/schemas/TransferDTO"
        creationDate:
          type: string
          format: date-time
        updateDate:
          type: string
          format: date-time
    TransferDTO:
      required:
        - amountCents
        - category
        - orgFiscalCode
        - orgName
        - remittanceInformation
      type: object
      properties:
        transferId:
          type: integer
          format: int64
        installmentId:
          type: integer
          format: int64
        orgFiscalCode:
          type: string
        orgName:
          type: string
        amountCents:
          type: integer
          format: int64
        remittanceInformation:
          type: string
        stampType:
          type: string
        stampHashDocument:
          type: string
        stampProvincialResidence:
          type: string
        iban:
          type: string
        postalIban:
          type: string
        category:
          type: string
        transferIndex:
          type: integer
          format: int64
    ReceiptDTO:
      type: object
      required:
        - receiptSource
        - paymentReceiptId
        - noticeNumber
        - orgFiscalCode
        - outcome
        - creditorReferenceId
        - paymentAmountCents
        - description
        - companyName
        - idPsp
        - pspCompanyName
        - idChannel
        - channelDescription
        - debtor
        - payer
      properties:
        receiptId:
          type: integer
          format: int64
        installmentId:
          type: integer
          format: int64
        ingestionFlowFileId:
          type: integer
          format: int64
        receiptOrigin:
          type: string
        paymentReceiptId:
          type: string
        noticeNumber:
          type: string
        paymentNote:
          type: string
        orgFiscalCode:
          type: string
        outcome:
          type: string
        creditorReferenceId:
          type: string
        paymentAmountCents:
          type: integer
          format: int64
        description:
          type: string
        companyName:
          type: string
        officeName:
          type: string
        idPsp:
          type: string
        pspFiscalCode:
          type: string
        pspPartitaIva:
          type: string
        pspCompanyName:
          type: string
        idChannel:
          type: string
        channelDescription:
          type: string
        paymentMethod:
          type: string
        feeCents:
          type: integer
          format: int64
        paymentDateTime:
          type: string
          format: date-time
        applicationDate:
          type: string
          format: date-time
        transferDate:
          type: string
          format: date-time
        standin:
          type: boolean
        debtor:
          $ref: "#/components/schemas/PersonDTO"
        payer:
          $ref: "#/components/schemas/PersonDTO"
        creationDate:
          type: string
          format: date-time
        updateDate:
          type: string
          format: date-time
    PersonDTO:
      required:
        - email
        - fullName
        - entityType
        - fiscalCode
      type: object
      properties:
        entityType:
          type: string
        fiscalCode:
          type: string
        fullName:
          type: string
        address:
          type: string
        civic:
          type: string
        postalCode:
          type: string
        location:
          type: string
        province:
          type: string
        nation:
          type: string
        email:
          type: string
    DebtPositionStatus:
      type: string
      enum:
        - TO_SYNC
        - REPORTED
        - PAID
        - PARTIALLY_PAID
        - CANCELLED
        - INVALID
        - EXPIRED
        - UNPAID
        - DRAFT
    DebtPositionOrigin:
      type: string
      enum:
        - ORDINARY
        - SPONTANEOUS
        - SECONDARY_ORG
        - RECEIPT_FILE
        - RECEIPT_PAGOPA
        - REPORTING_PAGOPA
    PaymentOptionStatus:
      type: string
      enum:
        - TO_SYNC
        - REPORTED
        - PAID
        - PARTIALLY_PAID
        - CANCELLED
        - INVALID
        - EXPIRED
        - UNPAID
        - DRAFT
    InstallmentStatus:
      type: string
      enum:
        - TO_SYNC
        - REPORTED
        - PAID
        - CANCELLED
        - INVALID
        - EXPIRED
        - UNPAID
        - DRAFT
    SyncStatusUpdateRequestDTO:
      type: object
      additionalProperties:
        $ref: "#/components/schemas/IupdSyncStatusUpdateDTO"
    IupdSyncStatusUpdateDTO:
      type: object
      properties:
        newStatus:
          $ref: "#/components/schemas/InstallmentStatus"
        iupdPagopa:
          type: string
    InstallmentSyncStatus:
      required:
        - syncStatusFrom
        - syncStatusTo
      type: object
      properties:
        syncStatusFrom:
          type: string
        syncStatusTo:
          type: string
    DebtPositionErrorDTO:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          enum:
            - DEBT_POSITION_BAD_REQUEST
            - DEBT_POSITION_CONFLICT
            - DEBT_POSITION_FORBIDDEN
            - DEBT_POSITION_GENERIC_ERROR
        message:
          type: string
